### ISSUE TITLE
Criteria in external dlls attempt to load twice in BuildAvailableCriteria

### ISSUE THREAD

**Issue by twaddell** [AndyButland/UmbracoPersonalisationGroups#14]
When an IPersonalisationGroupCriteria is created in a different class library project the PersonalisationGroupMatcher has 2 items with the same alias in typesImplementingInterface.
This causes a duplicate key error when AvailableCriteria.Add is called for the second time and so the personalisation package fails to load.

**Comment by AndyButland** [comment]
Thanks for flagging.  I've just put in a check to prevent attempting to load a criteria if one has been loaded with the same alias.
