### ISSUE TITLE
Install via NuGet after via Packages breaks site

### ISSUE THREAD

**Issue by cdecinkoKnight** [AndyButland/UmbracoPersonalisationGroups#18]
According to the directions, I should install via Packages and then via NuGet.  Doing so, caused most if not all of Umbraco 7 to be uninstalled and replaced with Umbraco 8.  This broke my site which relies on staying on Umbraco 7.  Many files were replaced just to get one DLL?

**Comment by AndyButland** [comment]
Sounds like you likely have installed the latest version, which does have a dependency on Umbraco 8.

For Umbraco 7, the latest version you should install is `Install-Package UmbracoPersonalisationGroups -Version 1.0.1`.  That shouldn't update anything else but if you really wanted to be sure you could use: `Install-Package UmbracoPersonalisationGroups -Version 1.0.1 -IgnoreDependencies`, which will only install the files necessary for the package.

Andy

**Comment by cdecinkoKnight** [comment]
Ok, that was it.  By default the newer version got installed.  Tried again forcing to v.1.0.1 and all seems ok.
