### ISSUE TITLE
Hide/show components in a uSkinned Theme

### ISSUE THREAD

**Issue by cdecinkoKnight** [AndyButland/UmbracoPersonalisationGroups#20]
Could this package be used with uSkinned starter kits/themes to hide/show components on a page based upon a Member Group?

**Comment by AndyButland** [comment]
I don't see why not no.  I'm not familiar with the uSkinned kits but this package just works against standard Umbraco concepts like `IPublishedContent`, so I'd expect you be able to use it to do what you describe if you apply the necessary custom code.
