### ISSUE TITLE
Criteria Dropdown not populated in umbraco 13

### ISSUE THREAD

**Issue by Bally77** [AndyButland/UmbracoPersonalisationGroups#46]
I am running Personalisation groups version 3.4 on umbraco 13.5.2 and the critera dropdown is not populated any ideas what i am missing

**Comment by AndyButland** [comment]
I've just run a local test with that version and I'm not seeing the problem.  Maybe check the request for `/App_Plugins/PersonalisationGroups/Criteria` and see if you are getting a 404 or error response in your browser console.

If so, you may be missing the configuration of the package in your `Program.cs` or `Startup.cs` class - see details [here](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/tree/main?tab=readme-ov-file#using-the-package).

**Comment by Bally77** [comment]
Hi 

The program.Cs changes have fixed the criteria problems 

Thank you
