### ISSUE TITLE
Update GetPickedGroups() and Others for UDI's from MNTP - 7.6+

### ISSUE THREAD

**Issue by paulsterling** [AndyButland/UmbracoPersonalisationGroups#7]
Looks like we'll need to update the GetPickedGroups() method, and likely others, to handle the UDI format Id's that come from pickers in 7.6+ - as opposed to CSV integer Id's in 7.5 and earlier.

**Comment by AndyButland** [comment]
Resolved in version 7.6 - see discussion on [this PR](https://github.com/AndyButland/UmbracoPersonalisationGroups/pull/8)
